/**
 * Mock/Fallback data for testing and development
 * Used when backend API is unavailable or returns no data
 */

export const mockProperties = [
  {
    id: 50117,
    title: "Brakusport Land",
    description: "Premium DTCP approved land in prime location",
    image: "/images/Modern-villa.jpg",
    price: 24000000,
    property_type: "Plot",
    status: "DTCP Approved",
    city: "Mumbai",
    bedrooms: 0,
    bathrooms: 0,
    area: 3815,
    rating: 4.9,
    verified: true,
    listingType: "For Sale",
  },
  {
    id: 50116,
    title: "Windlerboro Land",
    description: "Well-connected plot with excellent appreciation potential",
    image: "/images/Modern-villa.jpg",
    price: 23000000,
    property_type: "Plot",
    status: "DTCP Approved",
    city: "Chennai",
    bedrooms: 0,
    bathrooms: 0,
    area: 1889,
    rating: 4.8,
    verified: true,
    listingType: "For Sale",
  },
  {
    id: 50115,
    title: "Azusa Villa",
    description: "Spacious 4 BHK villa with modern amenities",
    image: "/images/Modern-villa.jpg",
    price: 24000000,
    property_type: "Villa",
    status: "For Sale",
    city: "Madurai",
    bedrooms: 4,
    bathrooms: 3,
    area: 1027,
    rating: 4.7,
    verified: true,
    listingType: "For Sale",
  },
  {
    id: 50114,
    title: "Luxe Apartment",
    description: "Modern 3 BHK apartment in premium complex",
    image: "/images/Modern-villa.jpg",
    price: 18000000,
    property_type: "Apartment",
    status: "Ready to Move",
    city: "Bangalore",
    bedrooms: 3,
    bathrooms: 2,
    area: 1250,
    rating: 4.8,
    verified: true,
    listingType: "For Sale",
  },
  {
    id: 50113,
    title: "Elite Residential Plot",
    description: "Corner plot in gated community with all amenities",
    image: "/images/Modern-villa.jpg",
    price: 15000000,
    property_type: "Plot",
    status: "Ready to Move",
    city: "Pune",
    bedrooms: 0,
    bathrooms: 0,
    area: 2000,
    rating: 4.6,
    verified: true,
    listingType: "For Sale",
  },
  {
    id: 50112,
    title: "Premium House",
    description: "Independent house with garden and parking",
    image: "/images/Modern-villa.jpg",
    price: 22000000,
    property_type: "House",
    status: "Ready to Move",
    city: "Hyderabad",
    bedrooms: 3,
    bathrooms: 2,
    area: 1500,
    rating: 4.9,
    verified: true,
    listingType: "For Sale",
  },
  {
    id: 50111,
    title: "Commercial Space",
    description: "Prime commercial property near main highway",
    image: "/images/Modern-villa.jpg",
    price: 28000000,
    property_type: "Commercial",
    status: "Ready to Move",
    city: "Chennai",
    bedrooms: 0,
    bathrooms: 0,
    area: 3500,
    rating: 4.7,
    verified: true,
    listingType: "For Sale",
  },
  {
    id: 50110,
    title: "Garden Villa",
    description: "Spacious villa with big garden and swimming pool",
    image: "/images/Modern-villa.jpg",
    price: 35000000,
    property_type: "Villa",
    status: "Ready to Move",
    city: "Mumbai",
    bedrooms: 5,
    bathrooms: 4,
    area: 2500,
    rating: 4.8,
    verified: true,
    listingType: "For Sale",
  },
  {
    id: 50109,
    title: "Compact Apartment",
    description: "Cozy 2 BHK apartment perfect for young professionals",
    image: "/images/Modern-villa.jpg",
    price: 12000000,
    property_type: "Apartment",
    status: "Ready to Move",
    city: "Delhi",
    bedrooms: 2,
    bathrooms: 1,
    area: 800,
    rating: 4.6,
    verified: true,
    listingType: "For Sale",
  },
  {
    id: 50108,
    title: "Beachfront Property",
    description: "Rare beachfront plot with stunning views",
    image: "/images/Modern-villa.jpg",
    price: 45000000,
    property_type: "Plot",
    status: "Ready to Move",
    city: "Goa",
    bedrooms: 0,
    bathrooms: 0,
    area: 5000,
    rating: 4.9,
    verified: true,
    listingType: "For Sale",
  },
  {
    id: 50107,
    title: "Tech Park Office",
    description: "Modern office space in IT corridor",
    image: "/images/Modern-villa.jpg",
    price: 50000000,
    property_type: "Commercial",
    status: "Ready to Move",
    city: "Bangalore",
    bedrooms: 0,
    bathrooms: 0,
    area: 4000,
    rating: 4.8,
    verified: true,
    listingType: "For Sale",
  },
  {
    id: 50106,
    title: "Heritage Bungalow",
    description: "Traditional bungalow with modern upgrades",
    image: "/images/Modern-villa.jpg",
    price: 32000000,
    property_type: "House",
    status: "Ready to Move",
    city: "Jaipur",
    bedrooms: 4,
    bathrooms: 3,
    area: 1800,
    rating: 4.7,
    verified: true,
    listingType: "For Sale",
  },
];

export const mockPagination = {
  totalPages: Math.ceil(mockProperties.length / 12),
  hasNextPage: true,
  hasPreviousPage: false,
  total: mockProperties.length,
};
